# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.api_helper import APIHelper
from spotifywebapi.models.episode_object import EpisodeObject


class ManyEpisodes(object):

    """Implementation of the 'ManyEpisodes' model.

    Attributes:
        episodes (List[EpisodeObject]): The model property of type
            List[EpisodeObject].
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "episodes": 'episodes'
    }

    def __init__(self,
                 episodes=None,
                 additional_properties=None):
        """Constructor for the ManyEpisodes class"""

        # Initialize members of the class
        self.episodes = episodes 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        episodes = None
        if dictionary.get('episodes') is not None:
            episodes = [EpisodeObject.from_dictionary(x) for x in dictionary.get('episodes')]
        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items() if k not in cls._names.values()},
            unboxing_function=lambda value: value)
        # Return an object of this model
        return cls(episodes,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'episodes={self.episodes!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'episodes={self.episodes!s}, '
                f'additional_properties={self.additional_properties!s})')
