# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.api_helper import APIHelper


class MeAlbumsRequest(object):

    """Implementation of the 'Me Albums Request' model.

    Attributes:
        ids (List[str]): A JSON array of the [Spotify
            IDs](/documentation/web-api/concepts/spotify-uris-ids). For
            example: `["4iV5W9uYEdYUVa79Axb7Rh",
            "1301WleyT98MSxVHPZCA6M"]`<br/>A maximum of 50 items can be
            specified in one request. _**Note**: if the `ids` parameter is
            present in the query string, any IDs listed here in the body will
            be ignored._
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "ids": 'ids'
    }

    _optionals = [
        'ids',
    ]

    def __init__(self,
                 ids=APIHelper.SKIP,
                 additional_properties=None):
        """Constructor for the MeAlbumsRequest class"""

        # Initialize members of the class
        if ids is not APIHelper.SKIP:
            self.ids = ids 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        ids = dictionary.get("ids") if dictionary.get("ids") else APIHelper.SKIP
        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items() if k not in cls._names.values()},
            unboxing_function=lambda value: value)
        # Return an object of this model
        return cls(ids,
                   additional_properties)

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'ids={(self.ids if hasattr(self, "ids") else None)!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'ids={(self.ids if hasattr(self, "ids") else None)!s}, '
                f'additional_properties={self.additional_properties!s})')
