# -*- coding: utf-8 -*-

"""
spotifywebapi

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from spotifywebapi.api_helper import APIHelper


class ResumePointObject(object):

    """Implementation of the 'ResumePointObject' model.

    Attributes:
        fully_played (bool): Whether or not the episode has been fully played
            by the user.
        resume_position_ms (int): The user's most recent position in the
            episode in milliseconds.
        additional_properties (Dict[str, Any]): The additional properties for
            the model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "fully_played": 'fully_played',
        "resume_position_ms": 'resume_position_ms'
    }

    _optionals = [
        'fully_played',
        'resume_position_ms',
    ]

    def __init__(self,
                 fully_played=APIHelper.SKIP,
                 resume_position_ms=APIHelper.SKIP,
                 additional_properties=None):
        """Constructor for the ResumePointObject class"""

        # Initialize members of the class
        if fully_played is not APIHelper.SKIP:
            self.fully_played = fully_played 
        if resume_position_ms is not APIHelper.SKIP:
            self.resume_position_ms = resume_position_ms 

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """

        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        fully_played = dictionary.get("fully_played") if "fully_played" in dictionary.keys() else APIHelper.SKIP
        resume_position_ms = dictionary.get("resume_position_ms") if dictionary.get("resume_position_ms") else APIHelper.SKIP
        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items() if k not in cls._names.values()},
            unboxing_function=lambda value: value)
        # Return an object of this model
        return cls(fully_played,
                   resume_position_ms,
                   additional_properties)

    @classmethod
    def validate(cls, dictionary):
        """Validates dictionary against class required properties

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            boolean : if dictionary is valid contains required properties.

        """

        if isinstance(dictionary, cls):
            return True

        if not isinstance(dictionary, dict):
            return False

        return True

    def __repr__(self):
        return (f'{self.__class__.__name__}('
                f'fully_played={(self.fully_played if hasattr(self, "fully_played") else None)!r}, '
                f'resume_position_ms={(self.resume_position_ms if hasattr(self, "resume_position_ms") else None)!r}, '
                f'additional_properties={self.additional_properties!r})')

    def __str__(self):
        return (f'{self.__class__.__name__}('
                f'fully_played={(self.fully_played if hasattr(self, "fully_played") else None)!s}, '
                f'resume_position_ms={(self.resume_position_ms if hasattr(self, "resume_position_ms") else None)!s}, '
                f'additional_properties={self.additional_properties!s})')
