name: PR Workflow

on:
  pull_request:
    branches:
      - main  # Make sure your default branch is 'main'
  workflow_dispatch:  # This allows manual run

jobs:
  sdk-check:
    name: SDK Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install SDK dependencies
        run: pip install -r requirements.txt

      - name: Install test tools (pytest)
        run: pip install pytest

      - name: (Optional) Build SDK
        run: |
          if [ -f setup.py ]; then
            python setup.py sdist bdist_wheel
          else
            echo "No setup.py found — skipping build step."
          fi

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    needs: sdk-check

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip install flake8

      - name: Run Code Quality Batch
        run: flake8 .  # Replace '.' with your folder if needed
