name: PR Workflow

on:
  pull_request:
    branches:
      - main  # Or whatever your main branch is
  workflow_dispatch:  # This allows you to manually run it from the Actions tab
jobs:
  sdk-check:
    name: SDK Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: pip install -r requirements.txt
      - name: Install test requirements
        run: pip install -r test-requirements.txt
      - name: Run tests

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    needs: sdk-check  # This makes sure Job 1 finishes first

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Code Quality Batch
        run: echo "🧹 Checking code quality..."  # Replace with your real code quality tool like eslint or flake8
