name: PR Workflow

on:
  pull_request:
    branches:
      - main  # Or whatever your main branch is

jobs:
  sdk-check:
    name: SDK Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build SDK
        run: echo "🔧 Building SDK..."  # Replace with your real build command, e.g., npm run build

      - name: Run SDK Tests
        run: echo "✅ Running SDK Tests..."  # Replace with real test command, e.g., npm test

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    needs: sdk-check  # This makes sure Job 1 finishes first

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Code Quality Batch
        run: echo "🧹 Checking code quality..."  # Replace with your real code quality tool like eslint or flake8
