name: PR Workflow

on:
  pull_request:
    branches:
      - main  # Make sure this matches your actual default branch name
  workflow_dispatch:  # This allows you to manually run it from the Actions tab
jobs:
  sdk-check:
    name: SDK Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Set a specific version to avoid matrix errors

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Install test requirements
        run: pip install -r test-requirements.txt

      - name: Run Tests
        run: pytest  # Or use your preferred test runner like unittest

  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    needs: sdk-check

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .  # You can customize this with config or paths
